#ifndef BEAUTY_LANG_LEXERCODES_H
#define BEAUTY_LANG_LEXERCODES_H

enum {
    TOKEN_START,
    TOKEN_ID,
    TOKEN_SEMICOLON,
    TOKEN_COLON,
    TOKEN_INT,
    TOKEN_CT_INT,
    TOKEN_FUN,
    TOKEN_EOF
};

#endif //BEAUTY_LANG_LEXERCODES_H
